name: CI for Develop Branch

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - develop

jobs:
  develop_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Workflow Details
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit Hash: ${{ github.sha }}"

  pull_request_job:
    needs: develop_workflow
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    steps:
      - uses: actions/checkout@v2
      - name: Pull Request Job Execution
        run: |
          echo "Running additional checks for PR to develop branch"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Body: ${{ github.event.pull_request.body }}"

  pull_request_accepted:
    runs-on: ubuntu-latest
    needs: pull_request_job
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v2
      - name: Handle Merged Pull Request
        run: |
          echo "Pull Request was merged successfully."
          echo "Merged PR Title: ${{ github.event.pull_request.title }}"

  pull_request_declined:
    runs-on: ubuntu-latest
    needs: pull_request_job
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false }}
    steps:
      - uses: actions/checkout@v2
      - name: Handle Declined Pull Request
        run: |
          echo "Pull Request was closed without merging."
          echo "Declined PR Title: ${{ github.event.pull_request.title }}"