name: CI for Workflow Configurations

on:
  push:
    branches:
      - 'feature/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y wget
      - name: Create and setup virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install poetry
      - name: Cache Poetry virtual environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Load virtual environment
        run: source .venv/bin/activate
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          poetry install

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          source .venv/bin/activate
          make test

  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Lint code
        run: |
          source .venv/bin/activate
          make lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Build package
        run: |
          source .venv/bin/activate
          make build

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Perform security scan
        run: |
          source .venv/bin/activate
          make security-scan

  feature_code_quality_check:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Code Quality Check
        run: echo "Simulating code quality check for feature branch."
