name: CI for Release Branches

on:
  push:
    branches:
      - 'release/**'

jobs:
  release_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Workflow Details
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit Hash: ${{ github.sha }}"

  release_build:
    runs-on: ubuntu-latest
    needs: release_workflow
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Build Process
        run: echo "Simulating build process for release branch."

  release_test:
    runs-on: ubuntu-latest
    needs: dummy_build
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Testing Process
        run: echo "Simulating testing process for release branch."

  release_code_quality_check:
    runs-on: ubuntu-latest
    needs: dummy_test
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Code Quality Check
        run: echo "Simulating code quality check for release branch."
