name: CI for Workflow Configurations

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          make install 

      - name: Run tests
        run: |
          make test

      - name: Lint code
        run: |
          make lint

      - name: Build package
        run: |
          make build

      - name: Perform security scan
        run: |
          make security-scan

      - name: Dummy Code Quality Check
        run: echo "Simulating code quality check for feature branch."
