name: CI for Hotfix Branches

on:
  push:
    branches:
      - 'hotfix/**'

jobs:
  hotfix_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Workflow Details
        run: |
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Commit Hash: ${{ github.sha }}"

  hotfix_build:
    runs-on: ubuntu-latest
    needs: hotfix_workflow
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Build Process
        run: echo "Simulating build process for hotfix branch."

  hotfix_test:
    runs-on: ubuntu-latest
    needs: hotfix_build
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Testing Process
        run: echo "Simulating testing process for hotfix branch."

  hotfix_code_quality_check:
    runs-on: ubuntu-latest
    needs: hotfix_test
    steps:
      - uses: actions/checkout@v4
      - name: Dummy Code Quality Check
        run: echo "Simulating code quality check for hotfix branch."
