name: Python Package Workflow

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  test:
    name: Test Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest -v

  release:
    name: Release Package
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry twine
          poetry install

      - name: Extract tag name and update version in pyproject.toml
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v//p')
          echo "Version from tag: $TAG_NAME"
          sed -i "s/version = \".*\"/version = \"$TAG_NAME\"/" pyproject.toml

      - name: Build and publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry run twine upload dist/* -u __token__ -p $PYPI_TOKEN

  test_release:
    name: Test Release Package
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/develop' &&
      startsWith(github.event.head_commit.message, 'v')
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry twine
          poetry install

      - name: Extract tag name and update version in pyproject.toml
        run: |
          TAG_NAME=$(echo $GITHUB_REF | sed -n 's/refs\/tags\/v//p')
          echo "Version from tag: $TAG_NAME"
          sed -i "s/version = \".*\"/version = \"$TAG_NAME\"/" pyproject.toml

      - name: Build and publish to Test PyPI
        env:
          PYPI_TEST_TOKEN: ${{ secrets.PYPI_TEST_TOKEN }}
        run: |
          poetry build
          poetry run twine upload --repository-url https://test.pypi.org/legacy/ dist/* -u __token__ -p $PYPI_TEST_TOKEN
